### DISCUSSION TITLE
Using binfmt/qemu within a k8s pod without docker.sock

### DISCUSSION THREAD

**Discussion by Shaked** [tonistiigi/binfmt#55] [Q&A] [answered]
Hey, I’m interested to use docker buildx with multi platform support. I have everything set except of QEMU as I cannot use `docker run` within my k8s pod as docker.sock is no longer available and cannot be mounted through the host/nodes.

How could I set this to work?

**Comment by morlay** [comment, marked as answer]
Once this PR merge, it could be easy to install QEMU in k8s

https://github.com/docker/buildx/pull/682

initContainer will be added when `--driver-opt=qemu.install=true`
```yaml
initContainers:
    - name: qemu
      image: 'tonistiigi/binfmt:latest'
      args:
        - '--install'
        - all
      imagePullPolicy: Always
      securityContext:
        privileged: true
```
