### ISSUE TITLE
qemu v9 regression: coredump during apt upgrade on fresh ubuntu

### ISSUE THREAD

**Issue by jonapich** [tonistiigi/binfmt#245]
- buildx: github.com/docker/buildx v0.20.1-desktop.2 aaf7c2bc7f9ec3afee1cec77d671845a4b57a0c8
- binfmt: binfmt/8714c54 qemu/v9.2.0 go/1.23.6

For the past few weeks, a couple of our dockerfiles can't build `linux/arm64` using emulation anymore:

```
#6 15.92 Preparing to unpack .../libc-bin_2.35-0ubuntu3.9_arm64.deb ...
#6 15.94 Unpacking libc-bin (2.35-0ubuntu3.9) over (2.35-0ubuntu3.8) ...
#6 16.15 Setting up libc-bin (2.35-0ubuntu3.9) ...
#6 16.25 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
#6 18.26 Segmentation fault (core dumped)
#6 18.30 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
#6 20.21 Segmentation fault (core dumped)
#6 20.21 dpkg: error processing package libc-bin (--configure):
#6 20.21  installed libc-bin package post-installation script subprocess returned error exit status 139
#6 20.22 Errors were encountered while processing:
#6 20.22  libc-bin
#6 20.29 E: Sub-process /usr/bin/dpkg returned an error code (1)
#6 ERROR: process "/bin/sh -c apt-get upgrade --assume-yes" did not complete successfully: exit code: 100
------
 > [3/3] RUN apt-get upgrade --assume-yes:
16.15 Setting up libc-bin (2.35-0ubuntu3.9) ...
16.25 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
18.26 Segmentation fault (core dumped)
18.30 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
20.21 Segmentation fault (core dumped)
20.21 dpkg: error processing package libc-bin (--configure):
20.21  installed libc-bin package post-installation script subprocess returned error exit status 139
20.22 Errors were encountered while processing:
20.22  libc-bin
20.29 E: Sub-process /usr/bin/dpkg returned an error code (1)
------
Dockerfile:4
--------------------
   2 |
   3 |     RUN apt-get update
   4 | >>> RUN apt-get upgrade --assume-yes
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get upgrade --assume-yes" did not complete successfully: exit code: 100
```

I have isolated the issue in here:

```
FROM ubuntu:22.04

RUN apt-get update
RUN apt-get upgrade --assume-yes
```

```
docker buildx build --platform linux/arm64 .
```

A workaround for the moment is to use `v8.1.5`:

```
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:qemu-v8.1.5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.21.2
          driver-opts: |
            image=moby/buildkit:buildx-stable-1
```

The issue has been reproduced on windows, linux, and in GitHub actions (linux)
