### ISSUE TITLE
Using binfmt/qemu within a k8s pod without docker.sock

### ISSUE THREAD

**Issue by Shaked** [tonistiigi/binfmt#52]
Hey, I’m interested to use docker buildx with multi platform support. I have everything set except of QEMU as I cannot use `docker run` within my k8s pod as docker.sock is no longer available and cannot be mounted through the host/nodes.

How could I set this to work?

**Comment by morlay** [comment]
Once this PR merge, it could be easy to install QEMU in k8s

https://github.com/docker/buildx/pull/682

initContainer will be added when `--driver-opt=qemu.install=true`
```
initContainers:
        - name: qemu
          image: 'tonistiigi/binfmt:latest'
          args:
            - '--install'
            - all
          imagePullPolicy: Always
          securityContext:
            privileged: true
```
